# Generated by Django 6.0.4 on 2026-04-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPurpura', '0003_cita_estado_cita_profesional_alter_cita_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('REPROGRAMADA', 'Reprogramada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('profesional', 'fecha', 'hora')},
        ),
    ]
