# Generated by Django 6.0.3 on 2026-04-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPurpura', '0002_cita_delete_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='cita',
            name='profesional',
            field=models.CharField(choices=[('Camila', 'Camila'), ('Lorena', 'Lorena'), ('Stefany', 'Stefany'), ('Clara', 'Clara'), ('Heidy', 'Heidy')], default='Camila', max_length=50),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.CharField(choices=[('manicure', 'Manicure'), ('pedicure', 'Pedicure'), ('pigmentacion de cejas', 'Pigmentación de cejas'), ('depilacion', 'Depilación')], max_length=100),
        ),
    ]
