# Generated by Django 6.0.2 on 2026-04-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPurpura', '0005_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='descripcion_no_atendida',
            field=models.TextField(blank=True, help_text='Descripción opcional si la cita no se realizó', null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('REPROGRAMADA', 'Reprogramada'), ('CANCELADA', 'Cancelada'), ('ATENDIDA', 'Atendida')], default='PENDIENTE', max_length=20),
        ),
    ]
